### ISSUE TITLE
As a new developper, I would like to retrieve the the movie db APIkey

### ISSUE THREAD

**Issue by mbreton** [js-republic/angular-demo#6]
Scenario:
- A checkout the project
- I follow instruction explained in readme
- when I run the app, the movieDB APIKey is missing because of the file is not commited (luckely :) )

Wanted :
I would like to find an easy way in the readme file (google drive or an another js-republic based authentication) to retrieve the missing file where the api key is put.

**Comment by VincentCordobes** [comment]
done
